#!/usr/bin/env bash
set -euo pipefail

binary="${1:?usage: test-parameter-service <binary>}"
qos_dir="$(mktemp -d)"

cleanup() {
  rm -rf "${qos_dir}"
}
trap cleanup EXIT

cat >"${qos_dir}/USER_QOS_PROFILES.xml" <<'XML'
<?xml version="1.0" encoding="UTF-8"?>
<dds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="http://community.rti.com/schema/7.3.0/rti_dds_qos_profiles.xsd"
     version="7.3.1">
  <qos_library name="LocalLoopbackDiscoveryLib">
    <qos_profile name="LocalLoopbackDiscoveryProfile" is_default_qos="true">
      <domain_participant_qos>
        <transport_builtin>
          <mask>SHMEM</mask>
        </transport_builtin>
        <discovery>
          <initial_peers>
            <element>builtin.shmem://</element>
          </initial_peers>
          <multicast_receive_addresses/>
        </discovery>
      </domain_participant_qos>
    </qos_profile>
  </qos_library>
</dds>
XML

cd "${qos_dir}"
timeout 20s "${binary}"
