set(CMAKE_SYSTEM_NAME QNX)
set(CMAKE_SYSTEM_PROCESSOR aarch64le)

set(QNX_TOOLCHAIN_TRIPLE aarch64-unknown-nto-qnx8.0.0)
set(QNX_TOOLCHAIN_VERSION 12.2.0)
get_filename_component(EVSN_REPO_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)

set(CMAKE_C_COMPILER "${EVSN_REPO_ROOT}/scripts/qnx-aarch64-gcc")
set(CMAKE_CXX_COMPILER "${EVSN_REPO_ROOT}/scripts/qnx-aarch64-g++")

set(CMAKE_AR "$ENV{QNX_HOST}/usr/bin/${QNX_TOOLCHAIN_TRIPLE}-ar")
set(CMAKE_RANLIB "$ENV{QNX_HOST}/usr/bin/${QNX_TOOLCHAIN_TRIPLE}-ranlib")
set(CMAKE_STRIP "$ENV{QNX_HOST}/usr/bin/${QNX_TOOLCHAIN_TRIPLE}-strip")
set(CMAKE_SYSROOT $ENV{QNX_TARGET})

set(CMAKE_LIBRARY_ARCHITECTURE ${CMAKE_SYSTEM_PROCESSOR})
list(APPEND CMAKE_SYSTEM_LIBRARY_PATH
    "${CMAKE_SYSROOT}/${CMAKE_SYSTEM_PROCESSOR}/lib"
    "${CMAKE_SYSROOT}/${CMAKE_SYSTEM_PROCESSOR}/usr/lib"
)
